/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DrugChainRegistry__factory } from "./DrugChainRegistry__factory";
export { IZkVerify__factory } from "./IZkVerify__factory";
