/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IZkVerify, IZkVerifyInterface } from "../IZkVerify";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "aggregationId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "leafDigest",
        type: "bytes32",
      },
      {
        internalType: "bytes32[]",
        name: "merklePath",
        type: "bytes32[]",
      },
      {
        internalType: "bool[]",
        name: "leafSide",
        type: "bool[]",
      },
    ],
    name: "verifyProofAttestation",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IZkVerify__factory {
  static readonly abi = _abi;
  static createInterface(): IZkVerifyInterface {
    return new Interface(_abi) as IZkVerifyInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IZkVerify {
    return new Contract(address, _abi, runner) as unknown as IZkVerify;
  }
}
