/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace DrugChainRegistry {
  export type CustodyRecordStruct = {
    fromEntityHash: BytesLike;
    toEntityHash: BytesLike;
    batchId: BytesLike;
    zkProofLeafDigest: BytesLike;
    batchCommitment: BytesLike;
    chainStep: BigNumberish;
    timestamp: BigNumberish;
    zkVerified: boolean;
  };

  export type CustodyRecordStructOutput = [
    fromEntityHash: string,
    toEntityHash: string,
    batchId: string,
    zkProofLeafDigest: string,
    batchCommitment: string,
    chainStep: bigint,
    timestamp: bigint,
    zkVerified: boolean
  ] & {
    fromEntityHash: string;
    toEntityHash: string;
    batchId: string;
    zkProofLeafDigest: string;
    batchCommitment: string;
    chainStep: bigint;
    timestamp: bigint;
    zkVerified: boolean;
  };
}

export interface DrugChainRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batches"
      | "custodyChain"
      | "entities"
      | "getFullCustodyChain"
      | "owner"
      | "recordCustodyTransfer"
      | "registerBatch"
      | "registerEntity"
      | "verifiedProofs"
      | "verifyBatchAtPharmacy"
      | "walletToEntity"
      | "zkVerifyProxy"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchFlaggedSuspicious"
      | "BatchRegistered"
      | "CustodyTransferred"
      | "CustodyVerified"
      | "EntityRegistered"
  ): EventFragment;

  encodeFunctionData(functionFragment: "batches", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "custodyChain",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "entities", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getFullCustodyChain",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordCustodyTransfer",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike[],
      boolean[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registerBatch",
    values: [BytesLike, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerEntity",
    values: [BytesLike, string, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedProofs",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyBatchAtPharmacy",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "walletToEntity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "zkVerifyProxy",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "batches", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "custodyChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "entities", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFullCustodyChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordCustodyTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerEntity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifiedProofs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyBatchAtPharmacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "walletToEntity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "zkVerifyProxy",
    data: BytesLike
  ): Result;
}

export namespace BatchFlaggedSuspiciousEvent {
  export type InputTuple = [batchId: BytesLike, reason: string];
  export type OutputTuple = [batchId: string, reason: string];
  export interface OutputObject {
    batchId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchRegisteredEvent {
  export type InputTuple = [
    batchId: BytesLike,
    manufacturerHash: BytesLike,
    drugName: string
  ];
  export type OutputTuple = [
    batchId: string,
    manufacturerHash: string,
    drugName: string
  ];
  export interface OutputObject {
    batchId: string;
    manufacturerHash: string;
    drugName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CustodyTransferredEvent {
  export type InputTuple = [
    batchId: BytesLike,
    from: BytesLike,
    to: BytesLike,
    chainStep: BigNumberish
  ];
  export type OutputTuple = [
    batchId: string,
    from: string,
    to: string,
    chainStep: bigint
  ];
  export interface OutputObject {
    batchId: string;
    from: string;
    to: string;
    chainStep: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CustodyVerifiedEvent {
  export type InputTuple = [
    batchId: BytesLike,
    zkProofLeafDigest: BytesLike,
    chainStep: BigNumberish
  ];
  export type OutputTuple = [
    batchId: string,
    zkProofLeafDigest: string,
    chainStep: bigint
  ];
  export interface OutputObject {
    batchId: string;
    zkProofLeafDigest: string;
    chainStep: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EntityRegisteredEvent {
  export type InputTuple = [
    entityIdHash: BytesLike,
    name: string,
    entityType: BigNumberish,
    wallet: AddressLike
  ];
  export type OutputTuple = [
    entityIdHash: string,
    name: string,
    entityType: bigint,
    wallet: string
  ];
  export interface OutputObject {
    entityIdHash: string;
    name: string;
    entityType: bigint;
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DrugChainRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): DrugChainRegistry;
  waitForDeployment(): Promise<this>;

  interface: DrugChainRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batches: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, bigint, boolean] & {
        batchId: string;
        manufacturerEntityHash: string;
        drugName: string;
        batchNumber: string;
        manufactureDate: bigint;
        expiryDate: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  custodyChain: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, string, string, string, bigint, bigint, boolean] & {
        fromEntityHash: string;
        toEntityHash: string;
        batchId: string;
        zkProofLeafDigest: string;
        batchCommitment: string;
        chainStep: bigint;
        timestamp: bigint;
        zkVerified: boolean;
      }
    ],
    "view"
  >;

  entities: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, boolean, string] & {
        entityIdHash: string;
        name: string;
        entityType: bigint;
        isActive: boolean;
        wallet: string;
      }
    ],
    "view"
  >;

  getFullCustodyChain: TypedContractMethod<
    [batchId: BytesLike],
    [DrugChainRegistry.CustodyRecordStructOutput[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  recordCustodyTransfer: TypedContractMethod<
    [
      batchId: BytesLike,
      toEntityHash: BytesLike,
      zkProofLeafDigest: BytesLike,
      batchCommitment: BytesLike,
      chainStep: BigNumberish,
      aggregationId: BigNumberish,
      merklePath: BytesLike[],
      leafSide: boolean[]
    ],
    [void],
    "nonpayable"
  >;

  registerBatch: TypedContractMethod<
    [
      batchId: BytesLike,
      drugName: string,
      batchNumber: string,
      expiryDate: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  registerEntity: TypedContractMethod<
    [
      entityIdHash: BytesLike,
      name: string,
      entityType: BigNumberish,
      wallet: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  verifiedProofs: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  verifyBatchAtPharmacy: TypedContractMethod<
    [batchId: BytesLike],
    [
      [boolean, bigint, bigint] & {
        isAuthentic: boolean;
        chainLength: bigint;
        lastVerifiedTimestamp: bigint;
      }
    ],
    "view"
  >;

  walletToEntity: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  zkVerifyProxy: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batches"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, bigint, boolean] & {
        batchId: string;
        manufacturerEntityHash: string;
        drugName: string;
        batchNumber: string;
        manufactureDate: bigint;
        expiryDate: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "custodyChain"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, string, string, string, bigint, bigint, boolean] & {
        fromEntityHash: string;
        toEntityHash: string;
        batchId: string;
        zkProofLeafDigest: string;
        batchCommitment: string;
        chainStep: bigint;
        timestamp: bigint;
        zkVerified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "entities"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, boolean, string] & {
        entityIdHash: string;
        name: string;
        entityType: bigint;
        isActive: boolean;
        wallet: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFullCustodyChain"
  ): TypedContractMethod<
    [batchId: BytesLike],
    [DrugChainRegistry.CustodyRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordCustodyTransfer"
  ): TypedContractMethod<
    [
      batchId: BytesLike,
      toEntityHash: BytesLike,
      zkProofLeafDigest: BytesLike,
      batchCommitment: BytesLike,
      chainStep: BigNumberish,
      aggregationId: BigNumberish,
      merklePath: BytesLike[],
      leafSide: boolean[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerBatch"
  ): TypedContractMethod<
    [
      batchId: BytesLike,
      drugName: string,
      batchNumber: string,
      expiryDate: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerEntity"
  ): TypedContractMethod<
    [
      entityIdHash: BytesLike,
      name: string,
      entityType: BigNumberish,
      wallet: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifiedProofs"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyBatchAtPharmacy"
  ): TypedContractMethod<
    [batchId: BytesLike],
    [
      [boolean, bigint, bigint] & {
        isAuthentic: boolean;
        chainLength: bigint;
        lastVerifiedTimestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "walletToEntity"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "zkVerifyProxy"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "BatchFlaggedSuspicious"
  ): TypedContractEvent<
    BatchFlaggedSuspiciousEvent.InputTuple,
    BatchFlaggedSuspiciousEvent.OutputTuple,
    BatchFlaggedSuspiciousEvent.OutputObject
  >;
  getEvent(
    key: "BatchRegistered"
  ): TypedContractEvent<
    BatchRegisteredEvent.InputTuple,
    BatchRegisteredEvent.OutputTuple,
    BatchRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CustodyTransferred"
  ): TypedContractEvent<
    CustodyTransferredEvent.InputTuple,
    CustodyTransferredEvent.OutputTuple,
    CustodyTransferredEvent.OutputObject
  >;
  getEvent(
    key: "CustodyVerified"
  ): TypedContractEvent<
    CustodyVerifiedEvent.InputTuple,
    CustodyVerifiedEvent.OutputTuple,
    CustodyVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "EntityRegistered"
  ): TypedContractEvent<
    EntityRegisteredEvent.InputTuple,
    EntityRegisteredEvent.OutputTuple,
    EntityRegisteredEvent.OutputObject
  >;

  filters: {
    "BatchFlaggedSuspicious(bytes32,string)": TypedContractEvent<
      BatchFlaggedSuspiciousEvent.InputTuple,
      BatchFlaggedSuspiciousEvent.OutputTuple,
      BatchFlaggedSuspiciousEvent.OutputObject
    >;
    BatchFlaggedSuspicious: TypedContractEvent<
      BatchFlaggedSuspiciousEvent.InputTuple,
      BatchFlaggedSuspiciousEvent.OutputTuple,
      BatchFlaggedSuspiciousEvent.OutputObject
    >;

    "BatchRegistered(bytes32,bytes32,string)": TypedContractEvent<
      BatchRegisteredEvent.InputTuple,
      BatchRegisteredEvent.OutputTuple,
      BatchRegisteredEvent.OutputObject
    >;
    BatchRegistered: TypedContractEvent<
      BatchRegisteredEvent.InputTuple,
      BatchRegisteredEvent.OutputTuple,
      BatchRegisteredEvent.OutputObject
    >;

    "CustodyTransferred(bytes32,bytes32,bytes32,uint8)": TypedContractEvent<
      CustodyTransferredEvent.InputTuple,
      CustodyTransferredEvent.OutputTuple,
      CustodyTransferredEvent.OutputObject
    >;
    CustodyTransferred: TypedContractEvent<
      CustodyTransferredEvent.InputTuple,
      CustodyTransferredEvent.OutputTuple,
      CustodyTransferredEvent.OutputObject
    >;

    "CustodyVerified(bytes32,bytes32,uint8)": TypedContractEvent<
      CustodyVerifiedEvent.InputTuple,
      CustodyVerifiedEvent.OutputTuple,
      CustodyVerifiedEvent.OutputObject
    >;
    CustodyVerified: TypedContractEvent<
      CustodyVerifiedEvent.InputTuple,
      CustodyVerifiedEvent.OutputTuple,
      CustodyVerifiedEvent.OutputObject
    >;

    "EntityRegistered(bytes32,string,uint8,address)": TypedContractEvent<
      EntityRegisteredEvent.InputTuple,
      EntityRegisteredEvent.OutputTuple,
      EntityRegisteredEvent.OutputObject
    >;
    EntityRegistered: TypedContractEvent<
      EntityRegisteredEvent.InputTuple,
      EntityRegisteredEvent.OutputTuple,
      EntityRegisteredEvent.OutputObject
    >;
  };
}
