/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface IZkVerifyInterface extends Interface {
  getFunction(nameOrSignature: "verifyProofAttestation"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "verifyProofAttestation",
    values: [BigNumberish, BytesLike, BytesLike[], boolean[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "verifyProofAttestation",
    data: BytesLike
  ): Result;
}

export interface IZkVerify extends BaseContract {
  connect(runner?: ContractRunner | null): IZkVerify;
  waitForDeployment(): Promise<this>;

  interface: IZkVerifyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  verifyProofAttestation: TypedContractMethod<
    [
      aggregationId: BigNumberish,
      leafDigest: BytesLike,
      merklePath: BytesLike[],
      leafSide: boolean[]
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "verifyProofAttestation"
  ): TypedContractMethod<
    [
      aggregationId: BigNumberish,
      leafDigest: BytesLike,
      merklePath: BytesLike[],
      leafSide: boolean[]
    ],
    [boolean],
    "view"
  >;

  filters: {};
}
